- hosts: localhost

  become: false
  gather_facts: false

  tasks:
    - name: "wypisz na ekran"
      ansible.builtin.debug:
        msg: "{{ hostvars[inventory_hostname] }}"
      loop: "{{ groups['all'] }}"

    - name: "wypisz na ekran"
      ansible.builtin.debug:
        msg: "{{ hostvars['apach02'] }}"

    - name: "wypisz na ekran"
      ansible.builtin.debug:
        msg: "{{ hostvars['apach02'].zmienna }}"
